// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageTracker.Accessors.Data;

#nullable disable

namespace PackageTracker.Accessors.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418212405_SeedDepotsAndDrones")]
    partial class SeedDepotsAndDrones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageTracker.Models.Depot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Depots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationId = 1,
                            Name = "Seward Depot"
                        },
                        new
                        {
                            Id = 2,
                            LocationId = 2,
                            Name = "Pawnee Lake Depot"
                        },
                        new
                        {
                            Id = 3,
                            LocationId = 3,
                            Name = "Lincoln Northwest Depot"
                        },
                        new
                        {
                            Id = 4,
                            LocationId = 4,
                            Name = "Waverly Depot"
                        },
                        new
                        {
                            Id = 5,
                            LocationId = 5,
                            Name = "Greenwood Depot"
                        },
                        new
                        {
                            Id = 6,
                            LocationId = 6,
                            Name = "Melia Depot"
                        },
                        new
                        {
                            Id = 7,
                            LocationId = 7,
                            Name = "Millard Depot"
                        },
                        new
                        {
                            Id = 8,
                            LocationId = 8,
                            Name = "Omaha Depot"
                        },
                        new
                        {
                            Id = 9,
                            LocationId = 9,
                            Name = "Depot at 27th and O St"
                        },
                        new
                        {
                            Id = 10,
                            LocationId = 10,
                            Name = "Depot at 84th and O St"
                        },
                        new
                        {
                            Id = 11,
                            LocationId = 11,
                            Name = "Depot at 84th St and Hwy 2"
                        });
                });

            modelBuilder.Entity("PackageTracker.Models.Drone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentDepotId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentPackageId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationDepotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HomeDepotId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentDepotId");

                    b.HasIndex("CurrentPackageId");

                    b.HasIndex("DestinationDepotId");

                    b.HasIndex("HomeDepotId");

                    b.ToTable("Drones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDepotId = 1,
                            HomeDepotId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CurrentDepotId = 1,
                            HomeDepotId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CurrentDepotId = 1,
                            HomeDepotId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CurrentDepotId = 2,
                            HomeDepotId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CurrentDepotId = 2,
                            HomeDepotId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CurrentDepotId = 2,
                            HomeDepotId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CurrentDepotId = 3,
                            HomeDepotId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CurrentDepotId = 3,
                            HomeDepotId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CurrentDepotId = 3,
                            HomeDepotId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CurrentDepotId = 4,
                            HomeDepotId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CurrentDepotId = 4,
                            HomeDepotId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CurrentDepotId = 4,
                            HomeDepotId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CurrentDepotId = 5,
                            HomeDepotId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            CurrentDepotId = 5,
                            HomeDepotId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CurrentDepotId = 5,
                            HomeDepotId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            CurrentDepotId = 6,
                            HomeDepotId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            CurrentDepotId = 6,
                            HomeDepotId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CurrentDepotId = 6,
                            HomeDepotId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            CurrentDepotId = 7,
                            HomeDepotId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            CurrentDepotId = 7,
                            HomeDepotId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            CurrentDepotId = 7,
                            HomeDepotId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            CurrentDepotId = 8,
                            HomeDepotId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            CurrentDepotId = 8,
                            HomeDepotId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            CurrentDepotId = 8,
                            HomeDepotId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            CurrentDepotId = 9,
                            HomeDepotId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 26,
                            CurrentDepotId = 9,
                            HomeDepotId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 27,
                            CurrentDepotId = 9,
                            HomeDepotId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            CurrentDepotId = 10,
                            HomeDepotId = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            CurrentDepotId = 10,
                            HomeDepotId = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = 30,
                            CurrentDepotId = 10,
                            HomeDepotId = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            CurrentDepotId = 11,
                            HomeDepotId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            CurrentDepotId = 11,
                            HomeDepotId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            CurrentDepotId = 11,
                            HomeDepotId = 11,
                            Status = 0
                        });
                });

            modelBuilder.Entity("PackageTracker.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 40.824939999999998,
                            Longitude = -97.096590000000006
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 40.826540000000001,
                            Longitude = -96.899500000000003
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 40.860590000000002,
                            Longitude = -96.729060000000004
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 40.900440000000003,
                            Longitude = -96.553669999999997
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 40.965670000000003,
                            Longitude = -96.403750000000002
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 41.086590000000001,
                            Longitude = -96.275989999999993
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 41.181780000000003,
                            Longitude = -96.120009999999994
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 41.222410000000004,
                            Longitude = -95.947500000000005
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 40.813279999999999,
                            Longitude = -96.68186
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 40.812989999999999,
                            Longitude = -96.607050000000001
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 40.735999999999997,
                            Longitude = -96.604479999999995
                        });
                });

            modelBuilder.Entity("PackageTracker.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationLocationId")
                        .HasColumnType("int");

                    b.Property<int>("OriginLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("OriginLocationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PackageTracker.Models.PackageStatusEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepotId")
                        .HasColumnType("int");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageStatusEvents");
                });

            modelBuilder.Entity("PackageTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PackageTracker.Models.Depot", b =>
                {
                    b.HasOne("PackageTracker.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PackageTracker.Models.Drone", b =>
                {
                    b.HasOne("PackageTracker.Models.Depot", "CurrentDepot")
                        .WithMany()
                        .HasForeignKey("CurrentDepotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PackageTracker.Models.Package", "CurrentPackage")
                        .WithMany()
                        .HasForeignKey("CurrentPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PackageTracker.Models.Depot", "DestinationDepot")
                        .WithMany()
                        .HasForeignKey("DestinationDepotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PackageTracker.Models.Depot", "HomeDepot")
                        .WithMany()
                        .HasForeignKey("HomeDepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentDepot");

                    b.Navigation("CurrentPackage");

                    b.Navigation("DestinationDepot");

                    b.Navigation("HomeDepot");
                });

            modelBuilder.Entity("PackageTracker.Models.Package", b =>
                {
                    b.HasOne("PackageTracker.Models.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PackageTracker.Models.Location", "OriginLocation")
                        .WithMany()
                        .HasForeignKey("OriginLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PackageTracker.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("OriginLocation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PackageTracker.Models.PackageStatusEvent", b =>
                {
                    b.HasOne("PackageTracker.Models.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PackageTracker.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depot");

                    b.Navigation("Package");
                });
#pragma warning restore 612, 618
        }
    }
}
